### ISSUE TITLE
Names outstanding contract issues

### ISSUE THREAD

**Issue by yubrew** [public-awesome/names#104]
- ~~basic flow deploy 00-06. add addr to wl w 2 per limit.~~
  - ~~test discount~~
  - ~~test multiple wl w addr~~
  - ~~test multiple wl no addr~~
  - ~~test multiple wl dup addr~~
- ~~confirm whitelist works with multiple whitelist~~
- ~~add descriptive events for indexer~~
- add fairburn for mint
- add verified optional field for text records and all the necessary sanitizing and checks

front end:
----

load test:
----
- minting random 100,000 names and monitoring gas
- check wl and minter wl can handle 5k addresses each, 5 wl on minter

admin test:
----
update / rm admin

**Comment by shanev** [comment]
I believe we have individual issues for these so not sure why we need a grab bag issue.
